### ISSUE TITLE
Change TagPack identifiers

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-tagpack-tool#20]
Currently, the tagpack filename serves as unique identifier in the DB. However, people could use the same filenames across tagpack collections. Therefore, I propose to support another field `prefix` as part of the config, which is then used to construct a unique identifier:

```
prefix: mytags
baseURI: https://github.com/somehwherer/my-tagpacks/blob/master
````

The ID of a TagPack is then: prefix + path relativ to config file

```mytags:packs/BTC/vasp1.yaml```

**Comment by mdragaschnig** [comment]
The relative path is also a requirement because of duplicate filenames inside a collection.
