### ISSUE TITLE
Add support for optional source_uri field

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-tagpack-tool#21]
A tag has a source (e.g.., GraphSense Public TagPack) and an optional source_uri (e.g., the tagpack URI)

**Comment by mdragaschnig** [comment]
@behas according to the official documentation https://github.com/graphsense/graphsense-tagpacks/tree/develop#what-is-an-attribution-tag
the `source` field is for URIs already. And all existing tagpacks do adhere to this convention.

What you describe above as source (e.g.., GraphSense Public TagPack), looks like title or description to me, and those fields already exist too.

**Comment by behas** [comment]
Good point. Let's discuss next week: we need to cover the following cases:

1.) tag is retrieved from some Web source:
source: https://archive.org/donate/cryptocurrency/

2.) tag is retrieved from 3rd party data source and the data source wants to provide a back-link
source: https://sometool.com/btc/some_address

3.) tag is retrieved from 3rd party data source; no backlink provided
source: some data source (no URI)

We could, of course, leave things as they are and display the tagpack title an creator instead. Let's discuss this in our next call.

**Comment by behas** [comment]
this is obsolete now

**Comment by mdragaschnig** [comment]
Updated documentation acordingly:
https://github.com/graphsense/graphsense-tagpack-tool/blob/master/README_tagpacks.md#tagpack-properties

**Comment by mdragaschnig** [comment]
Has been clarified in https://github.com/graphsense/graphsense-dashboard/issues/279
