### ISSUE TITLE
remove INSERTs from tagstore_schema.sql, use confidence.csv as data source

### ISSUE THREAD

**Issue by mdragaschnig** [graphsense/graphsense-tagpack-tool#29]

**Comment by behas** [comment]
almost fixed; @defconst could you add this to the docker file so that scores are ingested upon container startup:

    psql \
        -h $DBHOST \
        -p $DBPORT \
        -d $DB \
        -U $DBUSER \
        --password \
        -c "\copy tagstore.confidence(id,label,description,level) from 'tagpack/db/confidence.csv' delimiter ',' csv header;"

**Comment by behas** [comment]
@defconst merged into develop. Please integrate psql insert command into docker file.

**Comment by behas** [comment]
I think we should handle insert of confidence scores just as we handle ingest of abuse and entity taxonomies. So this is solved as soon as #35 is solved.
