### ISSUE TITLE
Consolidate confidence score handling

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-tagpack-tool#35]
Currently, confidence scores are duplicated: in confidence.csv and tagstore_schema.sql

Proposed solution: enhance tagpack-tool as follows

- [x] tagpack-tool confidence show -> list confidence scores
- [x] tagpack-tool confidence ingest -> ingest confidence scores into DB (-f to force overwrite)
- [x] remove confidence INSERT statements from tagstore_schema.sql

**Comment by mdragaschnig** [comment]
depends on https://github.com/graphsense/graphsense-tagpack-tool/issues/29

**Comment by cybersec-code** [comment]
Now the `confidence` parameter allows to `show` or `ingest` confidence scores
