### ISSUE TITLE
Consolidate TagPack-level properties

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-tagpack-tool#37]
Two issues with TagPack-level properties; to be discussed with @mdragaschnig 

- [x] The schema defined `creator` and `owner`. It turned out that in practice this mostly the same; we should consolidate this and eliminate the owner field
- [x] the `source` property is a tag-level field, but the db schema defines it as tagpack-level field; maybe remove it as well.

**Comment by behas** [comment]
@myrho is the tagpack source property used in the REST interface?

**Comment by myrho** [comment]
yes

**Comment by myrho** [comment]
sorry, no, `tagpack.source` is not used
