### ISSUE TITLE
Remove duplicate tags

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-tagpack-tool#38]
It can happen that the same creator inserts the same tag multiple times in several tagpacks; for instance, if tagpacks are generated automatically without filtering for duplicates. Therefore, we should automatically deduplicate them in the TagStore DB.

Query to identify and count duplicates:

````
SELECT
	t.address,
	t.label,
	t.source,
	tp.creator,
	COUNT(*)
FROM
	tag t,
	tagpack tp
WHERE
	t.tagpack = tp.id
GROUP BY
	t.address,
	t.label,
	t.source,
	tp.creator
HAVING
	COUNT(*) > 1
ORDER BY
	count DESC
````

Possible approaches:
- as DB function
- as function of the TagPack tool (analogous to materialized view updates)

**Comment by behas** [comment]
Here is the query to identify duplicate tags:

````
SELECT 
	t.id,
	t.address,
	t.label,
	t.source,
	tp.creator,
	ROW_NUMBER() OVER (PARTITION BY t.address, t.label, t.source, tp.creator) as row_num
FROM
	tag t,
	tagpack tp
WHERE
	t.tagpack = tp.id

````

...needs to packed into a delete query which deletes all rows with row_num > 1

**Comment by mdragaschnig** [comment]
Possibly retain newest tag.

**Comment by behas** [comment]
Fixed and commited into branch 38_duplicate_tags. @mdragaschnig please test, merge into develop and delete branch,
