### ISSUE TITLE
Normalize ETH addresses

### ISSUE THREAD

**Issue by myrho** [graphsense/graphsense-tagpack-tool#39]
Before insert, normalize ETH addressen (either lowercase or uppercase them).

**Comment by cybersec-code** [comment]
Just to keep it in mind, a (common) way to validate ETH addresses is using the "mixed-case checksum address encoding" (https://eips.ethereum.org/EIPS/eip-55). Normalize ETH addresses would prevent addresses from being validated using this method.

**Comment by behas** [comment]
I think in the tagpacks we should keep the addresses as they are (mixed case); but when ingesting ETH addresses into the tagstore, they should be automatically normalized to lower-case

**Comment by cybersec-code** [comment]
ETH addresses are now normalized before insertion into the db
