### ISSUE TITLE
Speed up address-to-cluster mapping

### ISSUE THREAD

**Issue by mdragaschnig** [graphsense/graphsense-tagpack-tool#4]

**Comment by behas** [comment]
@soad003 plz review the current implementation and share your ideas on how to speed up the mapping.

**Comment by soad003** [comment]
will do

**Comment by mdragaschnig** [comment]
Parallelise

https://github.com/graphsense/graphsense-tagpack-tool/blob/develop/bin/tagpack-tool#L399

**Comment by mdragaschnig** [comment]
During my tests, speedup was more than fourfold, nice! (6 workers vs. 1 worker)
