### ISSUE TITLE
Evaluate table design for table address_cluster_mapping

### ISSUE THREAD

**Issue by mdragaschnig** [graphsense/graphsense-tagpack-tool#45]
The columns

- gs_cluster_def_addr 
- gs_cluster_in_degr  
- gs_cluster_out_degr 

caused a [bug](https://github.com/graphsense/graphsense-tagpack-tool/issues/45) that required a [fix](https://github.com/graphsense/graphsense-tagpack-tool/commit/9a2899b964785aabb6b9eeeae98c619265ea058f), but
are not used for [tag resolving](https://github.com/graphsense/graphsense-REST/blob/develop/gsrest/db/tagstore.py). 

Can we drop them?

**Comment by behas** [comment]
isn't the definer address used by REST? In any case, I would keep it for the moment because it is useful for identifying clusters. The other two fields can be dropped if @myrho agrees.

**Comment by myrho** [comment]
The only columns used by the rest service are `gs_cluster_id`, `address` and `currency`
