### ISSUE TITLE
Integrate taxonomy files into tool

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-tagpack-tool#50]
Currently, taxonomies are loaded from external URIs, which requires each tagpack repo to be configured with the corresponding links. We should rather integrate the taxonomy source files (e.g., https://github.com/graphsense/DW-VA-Taxonomy/tree/master/_data) into the tagpack repo (just like the confidence scores) and ingest them from there.

**Comment by behas** [comment]
@defconst @mdragaschnig your opinion on that?

**Comment by mdragaschnig** [comment]
@behas  is this what you suggest?

* for concepts from the Interpol taxonomies: link to https://interpol-innovation-centre.github.io/DW-VA-Taxonomy/ accordingly
* https://github.com/graphsense/DW-VA-Taxonomy becomes **completely** obsolet, since
    * our own concepts we describe **solely** in the csv files
* the taxonomy csv files are moved to this repository

**Comment by behas** [comment]
yes, but instead of using the CSV files, we should use the underlying YAML files, which https://github.com/graphsense/DW-VA-Taxonomy/blob/master/_data/abuses.yaml

**Comment by soad003** [comment]
what was the reason we are not using the interpol version directly? https://github.com/INTERPOL-Innovation-Centre/DW-VA-Taxonomy

**Comment by mdragaschnig** [comment]
> what was the reason we are not using the interpol version directly? https://github.com/INTERPOL-Innovation-Centre/DW-VA-Taxonomy

The reason was diverging concepts.
