### ISSUE TITLE
Separate db refresh from tagpack ingest

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-tagpack-tool#55]
Currently, materialized view updates and duplicate tag removal is performed as part of the tagpack ingest process. It would be better to handle that separately on demand (e.g., nightly). Therefore, I propose to implement the following commands that execute these actions:

```
tagpack-tool tagstore refresh_views
tagpack-tool tagstore remove_duplicates
```

**Comment by mdragaschnig** [comment]
Done; it is important to remember to run refresh_views regularly to maintain data consistency.

Also added a respective note to the README https://github.com/graphsense/graphsense-tagpack-tool/tree/develop#important-keeping-data-consistency-after-tagpack-insertion
