### ISSUE TITLE
Harmonize tagpack-tool commands

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-tagpack-tool#59]
Currently, we have a bit of an uncontrolled growth of commands and arguments. I propose to re-structure the commands just as they are organized in modules:

````
tagpack-tool tagpack {validate, insert}
tagpack-tool taxonomy {list, show, insert}
tagpack-tool tagstore {init, update_cluster_mappings, refresh_views, remove_duplicates}
tagpack-tool quality {calculate, show}
````
Since quality scores are also a (simple) form of taxonomy, I also propose to integrate them into the taxonomy module.

The `tagpack-tool tagstore init` command could ingest all taxonomy files into the empty database.

**Comment by cybersec-code** [comment]
This is finally addressed in the pull request #62, which I think it's complete now
