### ISSUE TITLE
Speed up tagpack insert

### ISSUE THREAD

**Issue by mdragaschnig** [graphsense/graphsense-tagpack-tool#61]
https://github.com/graphsense/graphsense-tagpack-tool/blob/develop/bin/tagpack-tool#L356

**Comment by soad003** [comment]
@mdragaschnig we can close this issue right?

**Comment by soad003** [comment]
merged in 8cd22b131f7f6cdd1e7b906949b4bd0299de8883/ https://github.com/graphsense/graphsense-tagpack-tool/pull/96
