### ISSUE TITLE
Data formatting issue

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-tagpack-tool#69]
https://github.com/INTERPOL-Innovation-Centre/TagPackConverters/issues/26#issuecomment-1369855755

**Comment by wincentbalin** [comment]
See https://github.com/INTERPOL-Innovation-Centre/TagPackConverters/issues/26#issuecomment-1399611814

**Comment by mdragaschnig** [comment]
Closing as per https://github.com/INTERPOL-Innovation-Centre/TagPackConverters/issues/26#issuecomment-1405167705
