### ISSUE TITLE
Unclear default values

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-tagpack-tool#70]
A user asked on the default value of `is_cluster_definer`. The db schema says NULL; I guess we should either change this to FALSE or find another solution to point out defaults

https://github.com/INTERPOL-Innovation-Centre/TagPackConverters/issues/30

**Comment by mdragaschnig** [comment]
Additionally, an update to the documentation https://github.com/graphsense/graphsense-tagpacks/wiki/GraphSense-TagPacks#mapping-attribution-tags-to-utxo-clusters

**Comment by soad003** [comment]
I have updated the documentation, see revision 6 (https://github.com/graphsense/graphsense-tagpacks/wiki/GraphSense-TagPacks/1da6e77650c4fe5bc4d70d6ea151dccde6d9c161)

**Comment by mdragaschnig** [comment]
Thanks, I have also added my notes from our discussion to the wiki. If @behas is also content with the documentation, we can close this issue.

https://github.com/graphsense/graphsense-tagpacks/wiki/GraphSense-TagPacks#mapping-attribution-tags-to-utxo-clusters
