### ISSUE TITLE
Harmonize flagging public/private tags

### ISSUE THREAD

**Issue by soad003** [graphsense/graphsense-tagpack-tool#82]
In the tagpack tool we currently have 2 different options regarding marking tagspacks as public on the cli level there is the override flag --public. On the other hand there is the flag is_public directly in the tagpack file, which is confusing.

**Comment by mdragaschnig** [comment]
is_public is an optional Tagpack field, but if it's present, it overrides the commandline option.

**Comment by mdragaschnig** [comment]
Phase out field in tagpack file: show deprecation warning. Remove from schema in the future

Keep commandline flag.
